on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: |
            https://loftyvirus.github.io/feed.xml
          file: '../../profile/README.md'
          max_entry: 10
      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "docs: update feed" || true
          git push
