name: Update Blog Feed in README

on:
  schedule:
    - cron: '0 20 * * *'  # Runs daily at 20:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update blog feed in README
        uses: sarisia/actions-readme-feed@v1
        with:
          url: |
            https://loftyvirus.github.io/feed.xml
          file: 'profile/README.md'  # Ensuring the feed is added to README
          max_entry: 10  # Adjust this to control the number of feed items

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "docs: update README with latest blog feed" || true
          git push
