name: Update Repositories in README

on:
  schedule:
    - cron: '0 20 * * *'  # Runs daily at 20:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch LoftyVirus repositories
        run: |
          curl -s "https://api.github.com/users/loftyvirus/repos?per_page=100" | \
          jq -r '.[] | "- [" + .name + "](https://github.com/loftyvirus/" + .name + ")"' > repos.md

      - name: Update README with repositories inside feed section
        run: |
          # Extract the current content of the README
          README_CONTENT=$(cat profile/README.md)
          
          # Extract the part before <!-- feed start --> and after <!-- feed end -->
          BEFORE_FEED=$(echo "$README_CONTENT" | sed -n '/<!-- feed start -->/p' | sed 's/<!-- feed start -->//')
          AFTER_FEED=$(echo "$README_CONTENT" | sed -n '/<!-- feed end -->/p' | sed 's/<!-- feed end -->//')

          # Build the new content for the feed section
          FEED_CONTENT="<!-- feed start -->\n$(cat repos.md)\n<!-- feed end -->"

          # Combine everything and update the README
          echo -e "$BEFORE_FEED\n$FEED_CONTENT\n$AFTER_FEED" > profile/README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "docs: update README with list of repositories inside feed" || true
          git push
