name: Update Organization Repo Feed

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0  # Fetch full history

      - name: Ensure profile README.md exists
        run: |
          PROFILE_README=".github/profile/README.md"
          if [ ! -f "$PROFILE_README" ]; then
            mkdir -p .github/profile
            cat <<EOF > "$PROFILE_README"
# Loftyvirus Organization
_Welcome to Loftyvirus. Our focus is on building and deploying using various concepts, trying different tools and technologies._

## Updates
<!-- feed start -->
<!-- feed end -->
EOF
          fi

      - name: Fetch list of Loftyvirus organization repositories
        run: |
          curl -s "https://api.github.com/orgs/Loftyvirus/repos?per_page=100" | jq -r '.[].html_url' > repos.txt

      - name: Populate initial 10 repositories if feed is empty
        run: |
          PROFILE_README=".github/profile/README.md"
          FEED_START="<!-- feed start -->"
          FEED_END="<!-- feed end -->"

          if ! grep -q "http" "$PROFILE_README"; then
            echo "Adding first 10 repositories..."
            head -n 10 repos.txt | awk '{print "- [" $0 "](" $0 ")"}' > temp_repos.txt

            awk -v start="$FEED_START" -v end="$FEED_END" -v new_repos="$(cat temp_repos.txt)" '
              {print}
              $0 ~ start {print new_repos}
              $0 ~ end {exit}
            ' "$PROFILE_README" > temp.md && mv temp.md "$PROFILE_README"
          fi

      - name: Append new repositories
        run: |
          PROFILE_README=".github/profile/README.md"
          FEED_START="<!-- feed start -->"
          FEED_END="<!-- feed end -->"

          EXISTING_FEED=$(sed -n "/$FEED_START/,/$FEED_END/p" "$PROFILE_README")
          NEW_REPOS=""
          while read -r REPO; do
            if ! echo "$EXISTING_FEED" | grep -q "$REPO"; then
              NEW_REPOS+="- [$REPO]($REPO)\n"
            fi
          done < repos.txt

          if [ -n "$NEW_REPOS" ]; then
            sed -i "/$FEED_END/i $NEW_REPOS" "$PROFILE_README"
          fi

      - name: Commit and push changes if needed
        run: |
          git config --global user.name "Loftyvirus Bot"
          git config --global user.email "bot@loftyvirus.org"
          git add .github/profile/README.md
          git commit -m "Update repository feed" || echo "No changes to commit"
          git push
